export const issuesData = [
  // {
  //   id: "a8721f6sd6-6467-4b14-bb93-56b8633bbba1",
  //   title: "Handle Delete",
  //   description: "Enable menu link activation / deactivation ",
  //   due_date: "Jan 8",
  //   estimated_time: "1 hrs",
  //   status: "Done",
  //   priority: "Low",
  // },

  // {
  //   id: "a8721f6sddd6-6467-4b14-bb93-56b8633bbba1",
  //   title: "Customize confirm dialog Delete",
  //   description: "Enable menu link activation / deactivation ",
  //   due_date: "Jan 8",
  //   estimated_time: "1 hrs",
  //   status: "Open",
  //   priority: "Low",
  // },
  // {
  //   id: "a879921f66-6467-4b14-bb93-56b8633bbba1",
  //   title: "App Ux enhancements ",
  //   description: "Enable menu link activation / deactivation ",
  //   due_date: "Jan 9",
  //   estimated_time: "3 hrs",
  //   status: "In progress",
  //   priority: "medium",
  // },
  {
    id: "a8721f66-64adddda-4b14-bb93-56b8633bbba1",
    title: "Global state management.",
    description: "Handle app authorzation.",
    due_date: "Jan 8",
    estimated_time: "3 hrs",
    status: "Done",
    priority: "High",
  },
  {
    id: "accd5223-edc1-4c92-a718-11aa03d87462",
    title: "Setting up the app",
    description: "Setting up the app",
    due_date: "Jan 7",
    estimated_time: "3 hrs",
    status: "Done",
    priority: "Medium",
  },
  {
    id: "1e823861-6566-4b47-9767-744a1eaa5cde",
    title: "Designing respective screens",
    description: "Designing respective screens.",
    due_date: "Jan 8",
    estimated_time: "3 hrs",
    status: "In progress",
    priority: "High",
  },
  // {
  //   id: "a8721f66-64aa-4b14-bb93-56b8633bbba1",
  //   title: "Global state management.",
  //   description: "Handle app authorzation.",
  //   due_date: "Jan 8",
  //   estimated_time: "3 hrs",
  //   status: "Done",
  //   priority: "High",
  // },
  // {
  //   id: "a8721f66-6467-4b14-bb93-56b8633bbba1",
  //   title: "Enable menu link activation / deactivation ",
  //   description: "Enable menu link activation / deactivation ",
  //   due_date: "Jan 9",
  //   estimated_time: "3 hrs",
  //   status: "Done",
  //   priority: "Low",
  // },
  // {
  //   id: "a5cb9fae2-7ff0-4e73-82c9-c68355d0288d",
  //   title: "Dashboard Filters not working",
  //   description: "Dashboard Filters not working",
  //   due_date: "Jan 9",
  //   estimated_time: "3 hrs",
  //   status: "Open",
  //   priority: "Low",
  // },
];

export const statusData = [
  { key: "1", value: "Mobiles", disabled: true },
  { key: "2", value: "Appliances" },
  { key: "3", value: "Cameras" },
  { key: "4", value: "Computers", disabled: true },
  { key: "5", value: "Vegetables" },
  { key: "6", value: "Diary Products" },
  { key: "7", value: "Drinks" },
];
